name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: npm run build

      - name: Deploy to server
        env:
          SCP_PASSWORD: ${{ secrets.SCP_PASSWORD }}
        run: |
          sshpass -p $SCP_PASSWORD scp -r ./dist/* jn@santa.jn.sfc.keio.ac.jp:/var/www/html
